intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

./: lib{mine}: {hxx ixx txx cxx}{** -mine -version} \
               {hxx            }{          version} \
               {hxx ixx     cxx}{    mine         } $impl_libs $intf_libs

hxx{version}: in{version} $src_root/manifest

# Command-line interface (CLI)
#
# Generate C++ command line interface from description files.
# https://www.codesynthesis.com/projects/cli/doc/cli.xhtml
#
if $cli.configured
{
  cli.options += -I $src_root
  cli.options += --std c++11
  cli.options += --guard-prefix MINE
  cli.options += --include-prefix libmine
  cli.options += --include-with-brackets
  cli.options += --cli-namespace mine::cli

  # Recipe configuration.
  #
  cli.cxx{*}:
  {
    # Distribute generated CLI files and preserve them during src cleanup
    # to maintain consistent source state across builds.
    #
    dist = true
    clean = ($src_root != $out_root)

    # Copy generated code back to src during forwarded configuration
    # to maintain single source of truth in repository.
    #
    backlink = overwrite
  }

  cli.cxx{mine}: cli{mine}
  {
    cli.options += --generate-parse
    cli.options += --suppress-undocumented
    cli.options += --long-usage
    cli.options += --ansi-color # bold/underline only
    cli.options += --ascii-tree
  }
}

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

obja{*}: cxx.poptions += -DLIBMINE_STATIC_BUILD
objs{*}: cxx.poptions += -DLIBMINE_SHARED_BUILD

# Export options.
#
lib{mine}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{mine}: cxx.export.poptions += -DLIBMINE_STATIC
libs{mine}: cxx.export.poptions += -DLIBMINE_SHARED

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{mine}: bin.lib.version = "-$version.project_id"
else
  lib{mine}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libmine/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/libmine/
  install.subdirs = true
}
